name: Custom domain
description: Request a custom domain managed by NumFOCUS for your project website, docs etc
labels: ["Request - Custom Domain"]

body:
  - type: input
    id: project
    attributes:
      label: Project or community
      description: >
        Please provide what NumFOCUS sponsored project, or user group you represent
    validations:
      required: true

  - type: checkboxes
    id: is_new
    attributes:
      label: New domain request?
      options:
        - label: >
            This request is for creating the DNS of an NEW domain (leave unchecked if requesting an update)

  - type: input
    id: domain
    attributes:
      label: Domain
      description: >
        Please provide what domain you are requesting
    validations:
      required: true

  - type: textarea
    id: dns
    attributes:
      label: DNS
      description: >
        Please provide what DNS records do you need for the subdomain (e.g. `A 8.8.8.8` or `CNAME you.github.io`)
    validations:
      required: true

  - type: textarea
    id: observations
    attributes:
      label: Observations
      description: >
        Please let us know if there is any other information you'd like to provide
    validations:
      required: true
